### ISSUE TITLE
HEY CHADS, TAKE A LOOK AT $omni

### ISSUE THREAD

**Issue by pmt9819** [Gitcatsol/gitcat#55]
A good coin with a strong, active community never die. 

![IMG_9672](https://github.com/user-attachments/assets/0aea704a-5936-4bfe-b0ef-cbbfd1f9f2fe)

CA: 24hHaxPLbZXBZQwGis2bqkpCNE2qb83VoVzm7T7Wpump

**Comment by Aristhodle** [comment]
suck my balls
